# Generated by Django 2.2 on 2019-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('auditorium', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_schools.Catalog')),
            ],
        ),
    ]
