# Generated by Django 2.2 on 2019-05-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_schools', '0002_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='limit',
        ),
        migrations.AddField(
            model_name='training',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
