# Generated by Django 2.2 on 2019-05-04 19:09

from django.db import migrations


def gen_catalogs(apps, schema_editor):
    Catalog = apps.get_model('my_schools', 'Catalog')
    for catalog in Catalog.objects.all():
        catalog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('my_schools', '0002_training'),
    ]

    operations = [
        migrations.RunPython(gen_catalogs),
    ]
