# Generated by Django 2.1.7 on 2019-05-27 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_schools', '0004_training_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='participant',
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
